enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  c0cca395-ed07-4593-ab29-93003c01cd30: # NDMaddhouse
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
