enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  c0cca395-ed07-4593-ab29-93003c01cd30: # NDMaddhouse
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
